//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationAutomationSystem.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEducationEntities4 : DbContext
    {
        public DbEducationEntities4()
            : base("name=DbEducationEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ilceler> ilceler { get; set; }
        public virtual DbSet<iller> iller { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLACADEMICIAN> TBLACADEMICIAN { get; set; }
        public virtual DbSet<TBLADMINLOGIN> TBLADMINLOGIN { get; set; }
        public virtual DbSet<TBLDEPARTMENT> TBLDEPARTMENT { get; set; }
        public virtual DbSet<TBLLESSON> TBLLESSON { get; set; }
        public virtual DbSet<TBLNOTE> TBLNOTE { get; set; }
        public virtual DbSet<TBLNOTIFICATION> TBLNOTIFICATION { get; set; }
        public virtual DbSet<TBLSTUDENT> TBLSTUDENT { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
        public virtual DbSet<View_2> View_2 { get; set; }
        public virtual DbSet<TBLTODOLIST> TBLTODOLIST { get; set; }
    }
}
