//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationAutomationSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLACADEMICIAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLACADEMICIAN()
        {
            this.TBLLESSON = new HashSet<TBLLESSON>();
            this.TBLNOTE = new HashSet<TBLNOTE>();
        }
    
        public int AcademicianID { get; set; }
        public string AcademicianTRNumber { get; set; }
        public string AcademicianName { get; set; }
        public string AcademicianSurname { get; set; }
        public Nullable<System.DateTime> AcademicianBirthDate { get; set; }
        public string AcademicianGender { get; set; }
        public string AcademicianPassword { get; set; }
        public string AcademicianConfirmPassword { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> AcademicianCity { get; set; }
        public Nullable<int> AcademicianDistrict { get; set; }
        public string AcademicianAddress { get; set; }
        public string AcademicianPhoneNumber { get; set; }
        public string AcademicianMail { get; set; }
        public string AcademicianImage { get; set; }
    
        public virtual iller iller { get; set; }
        public virtual TBLDEPARTMENT TBLDEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLLESSON> TBLLESSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNOTE> TBLNOTE { get; set; }
    }
}
