//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationAutomationSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLLESSON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLLESSON()
        {
            this.TBLNOTE = new HashSet<TBLNOTE>();
        }
    
        public int LessonID { get; set; }
        public string LessonName { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> Academician { get; set; }
    
        public virtual TBLACADEMICIAN TBLACADEMICIAN { get; set; }
        public virtual TBLDEPARTMENT TBLDEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNOTE> TBLNOTE { get; set; }
    }
}
