//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationAutomationSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLNOTE
    {
        public int NoteID { get; set; }
        public Nullable<byte> MidtermExam { get; set; }
        public Nullable<byte> FinalExam { get; set; }
        public Nullable<decimal> Average { get; set; }
        public Nullable<int> Lesson { get; set; }
        public Nullable<int> Student { get; set; }
        public Nullable<int> Academician { get; set; }
    
        public virtual TBLACADEMICIAN TBLACADEMICIAN { get; set; }
        public virtual TBLLESSON TBLLESSON { get; set; }
        public virtual TBLSTUDENT TBLSTUDENT { get; set; }
    }
}
