//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationAutomationSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLNOTIFICATION
    {
        public int NotificationID { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public string NotificationTitle { get; set; }
        public string NotificationDescription { get; set; }
    }
}
