//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationAutomationSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTODOLIST
    {
        public int ToDoListID { get; set; }
        public Nullable<System.DateTime> ToDoListDate { get; set; }
        public string ToDoListTitle { get; set; }
        public string ToDoListContent { get; set; }
        public Nullable<int> Student { get; set; }
    
        public virtual TBLSTUDENT TBLSTUDENT { get; set; }
    }
}
