//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationAutomationSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int NoteID { get; set; }
        public Nullable<byte> MidtermExam { get; set; }
        public Nullable<byte> FinalExam { get; set; }
        public string LessonName { get; set; }
        public string StudentName { get; set; }
        public string StudentSurname { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<decimal> Average { get; set; }
    }
}
