//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationAutomationSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EducationAutomationSystem.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre başarıyla değiştirildi, program yeniden başlatılıyor..
        /// </summary>
        internal static string adminsifredegisti {
            get {
                return ResourceManager.GetString("adminsifredegisti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres boş bırakılamaz..
        /// </summary>
        internal static string adresbos {
            get {
                return ResourceManager.GetString("adresbos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen Adı en az 2 karakter olmalıdır..
        /// </summary>
        internal static string akademisyenadi2karakterdenaz {
            get {
                return ResourceManager.GetString("akademisyenadi2karakterdenaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen Adı boş bırakılamaz..
        /// </summary>
        internal static string akademisyenadibos {
            get {
                return ResourceManager.GetString("akademisyenadibos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir akademisyen seçiniz..
        /// </summary>
        internal static string akademisyenbos {
            get {
                return ResourceManager.GetString("akademisyenbos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen panelinden çıkmak istiyor musunuz?.
        /// </summary>
        internal static string akademisyencikis {
            get {
                return ResourceManager.GetString("akademisyencikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} T.C. numaralı akademisyen başarılı bir şekilde güncellendi..
        /// </summary>
        internal static string akademisyenguncellendi {
            get {
                return ResourceManager.GetString("akademisyenguncellendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} T.C. numaralı akademisyen başarılı bir şekilde kaydedildi..
        /// </summary>
        internal static string akademisyenkaydedildi {
            get {
                return ResourceManager.GetString("akademisyenkaydedildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen olabilmesi için yaşı 21 olmalıdır..
        /// </summary>
        internal static string akademisyenolmayasi {
            get {
                return ResourceManager.GetString("akademisyenolmayasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Numaralı akademisyeni silmek istiyor musunuz?.
        /// </summary>
        internal static string akademisyensil {
            get {
                return ResourceManager.GetString("akademisyensil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} T.C. Numaralı akademisyen başarılı bir şekilde silindi..
        /// </summary>
        internal static string akademisyensilindi {
            get {
                return ResourceManager.GetString("akademisyensilindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen silmek istediğiniz bir akademisyen seçiniz..
        /// </summary>
        internal static string akademisyensilmebos {
            get {
                return ResourceManager.GetString("akademisyensilmebos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen Soyadı en az 2 karakter olmalıdır..
        /// </summary>
        internal static string akademisyensoyadi2karakterdenaz {
            get {
                return ResourceManager.GetString("akademisyensoyadi2karakterdenaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen Soyadı boş bırakılamaz..
        /// </summary>
        internal static string akademisyensoyadibos {
            get {
                return ResourceManager.GetString("akademisyensoyadibos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alanlar boş geçilemez!.
        /// </summary>
        internal static string alanlarbos {
            get {
                return ResourceManager.GetString("alanlarbos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anne adı en az 2 karakter olmalıdır..
        /// </summary>
        internal static string anneadi2karakterdenaz {
            get {
                return ResourceManager.GetString("anneadi2karakterdenaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anne adı boş bırakılamaz..
        /// </summary>
        internal static string anneadibos {
            get {
                return ResourceManager.GetString("anneadibos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} T.C. Numarası mevcut..
        /// </summary>
        internal static string ayniakademisyentc {
            get {
                return ResourceManager.GetString("ayniakademisyentc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adında bir bölüm mevcut..
        /// </summary>
        internal static string aynibolum {
            get {
                return ResourceManager.GetString("aynibolum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaten {0} isminde bir ders mevcut..
        /// </summary>
        internal static string aynidersadi {
            get {
                return ResourceManager.GetString("aynidersadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} T.C. Numarası mevcut..
        /// </summary>
        internal static string ayniogrencitc {
            get {
                return ResourceManager.GetString("ayniogrencitc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Okul Numarası mevcut..
        /// </summary>
        internal static string ayniokulno {
            get {
                return ResourceManager.GetString("ayniokulno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baba adı en az 2 karakter olmalıdır..
        /// </summary>
        internal static string babaadi2karakterdenaz {
            get {
                return ResourceManager.GetString("babaadi2karakterdenaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baba adı boş bırakılamaz..
        /// </summary>
        internal static string babaadibos {
            get {
                return ResourceManager.GetString("babaadibos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        internal static string bilgi {
            get {
                return ResourceManager.GetString("bilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm adı en az 5 karakterden oluşmalıdır..
        /// </summary>
        internal static string bolum5karakterdenaz {
            get {
                return ResourceManager.GetString("bolum5karakterdenaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adında bir bölüm bulunamadı..
        /// </summary>
        internal static string bolumadimevcutolmayanguncelleme {
            get {
                return ResourceManager.GetString("bolumadimevcutolmayanguncelleme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm adı boş bırakılamaz..
        /// </summary>
        internal static string bolumbos {
            get {
                return ResourceManager.GetString("bolumbos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adlı bölüm başarılı bir şekilde güncellendi..
        /// </summary>
        internal static string bolumguncellendi {
            get {
                return ResourceManager.GetString("bolumguncellendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adlı bölüm başarılı bir şekilde kaydedildi..
        /// </summary>
        internal static string bolumkaydedildi {
            get {
                return ResourceManager.GetString("bolumkaydedildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adlı bölümü silmek istiyor musunuz?.
        /// </summary>
        internal static string bolumsil {
            get {
                return ResourceManager.GetString("bolumsil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adlı bölüm başarılı bir şekilde silindi..
        /// </summary>
        internal static string bolumsilindi {
            get {
                return ResourceManager.GetString("bolumsilindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen silmek istediğiniz bir bölüm ismi seçiniz..
        /// </summary>
        internal static string bolumsilmebos {
            get {
                return ResourceManager.GetString("bolumsilmebos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesapla.
        /// </summary>
        internal static string BtnCalculate {
            get {
                return ResourceManager.GetString("BtnCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal Et.
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        internal static string BtnChange {
            get {
                return ResourceManager.GetString("BtnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEÇİNİZ.
        /// </summary>
        internal static string BtnChoose {
            get {
                return ResourceManager.GetString("BtnChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        internal static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru Listesi.
        /// </summary>
        internal static string BtnNotificationList {
            get {
                return ResourceManager.GetString("BtnNotificationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göster/Gizle.
        /// </summary>
        internal static string ChkConfirmPassword {
            get {
                return ResourceManager.GetString("ChkConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göster/Gizle.
        /// </summary>
        internal static string ChkCurrentPassword {
            get {
                return ResourceManager.GetString("ChkCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göster/Gizle.
        /// </summary>
        internal static string ChkNewPassword {
            get {
                return ResourceManager.GetString("ChkNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göster/Gizle.
        /// </summary>
        internal static string ChkPassword {
            get {
                return ResourceManager.GetString("ChkPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolayı Göster/Gizle.
        /// </summary>
        internal static string ChkShowHidePassword {
            get {
                return ResourceManager.GetString("ChkShowHidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        internal static string çıkışAdminToolStripMenuItem {
            get {
                return ResourceManager.GetString("çıkışAdminToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        internal static string çıkışAkademisyenToolStripMenuItem {
            get {
                return ResourceManager.GetString("çıkışAkademisyenToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        internal static string çıkışOgrenciToolStripMenuItem {
            get {
                return ResourceManager.GetString("çıkışOgrenciToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders adı en az 5 karakter olmalıdır..
        /// </summary>
        internal static string dersadi5karakterdenaz {
            get {
                return ResourceManager.GetString("dersadi5karakterdenaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders adı boş bırakılamaz..
        /// </summary>
        internal static string dersadibos {
            get {
                return ResourceManager.GetString("dersadibos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen silmek istediğiniz bir ders seçiniz..
        /// </summary>
        internal static string dersbos {
            get {
                return ResourceManager.GetString("dersbos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dersi başarılı bir şekilde güncellendi..
        /// </summary>
        internal static string dersguncellendi {
            get {
                return ResourceManager.GetString("dersguncellendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dersi başarıyla kaydedildi..
        /// </summary>
        internal static string derskaydedildi {
            get {
                return ResourceManager.GetString("derskaydedildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dersini silmek istiyor musunuz?.
        /// </summary>
        internal static string derssil {
            get {
                return ResourceManager.GetString("derssil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dersi başarılı bir şekilde silindi..
        /// </summary>
        internal static string derssilindi {
            get {
                return ResourceManager.GetString("derssilindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru başlığı boş bırakılamaz..
        /// </summary>
        internal static string duyurubasligibos {
            get {
                return ResourceManager.GetString("duyurubasligibos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen silmek istediğiniz bir duyuru seçiniz..
        /// </summary>
        internal static string duyurubos {
            get {
                return ResourceManager.GetString("duyurubos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} duyurusu başarılı bir şekilde eklendi..
        /// </summary>
        internal static string duyurueklendi {
            get {
                return ResourceManager.GetString("duyurueklendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adlı duyuru başarılı bir şekilde güncellendi..
        /// </summary>
        internal static string duyuruguncellendi {
            get {
                return ResourceManager.GetString("duyuruguncellendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru içeriği boş bırakılamaz..
        /// </summary>
        internal static string duyuruicerigibos {
            get {
                return ResourceManager.GetString("duyuruicerigibos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adlı duyuruyu silmek istiyor musunuz?.
        /// </summary>
        internal static string duyurusil {
            get {
                return ResourceManager.GetString("duyurusil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adlı duyuru başarılı bir şekilde silindi..
        /// </summary>
        internal static string duyurusilindi {
            get {
                return ResourceManager.GetString("duyurusilindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Kimlik Numarası 11 Karakter Olmalıdır!.
        /// </summary>
        internal static string errorprovidertc {
            get {
                return ResourceManager.GetString("errorprovidertc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eski şifreniz hatalıdır!.
        /// </summary>
        internal static string eskisifrehatali {
            get {
                return ResourceManager.GetString("eskisifrehatali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eski şifre ile yeni şifre aynı olmamalıdır!.
        /// </summary>
        internal static string eskiyenisifrelerayni {
            get {
                return ResourceManager.GetString("eskiyenisifrelerayni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizle.
        /// </summary>
        internal static string gizleToolStripMenuItem {
            get {
                return ResourceManager.GetString("gizleToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göster.
        /// </summary>
        internal static string gösterToolStripMenuItem {
            get {
                return ResourceManager.GetString("gösterToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Bilgileri.
        /// </summary>
        internal static string groupBox1 {
            get {
                return ResourceManager.GetString("groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Bilgileri.
        /// </summary>
        internal static string groupBox2 {
            get {
                return ResourceManager.GetString("groupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Bilgileri.
        /// </summary>
        internal static string groupBox3 {
            get {
                return ResourceManager.GetString("groupBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen Bilgileri.
        /// </summary>
        internal static string groupBox4 {
            get {
                return ResourceManager.GetString("groupBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Bilgileri.
        /// </summary>
        internal static string groupBox5 {
            get {
                return ResourceManager.GetString("groupBox5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        internal static string hata {
            get {
                return ResourceManager.GetString("hata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalı güvenlik kodu girişi!.
        /// </summary>
        internal static string hataliguvenlikkodugirisi {
            get {
                return ResourceManager.GetString("hataliguvenlikkodugirisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalı T.C. numarası, kullanıcı adı veya şifre!.
        /// </summary>
        internal static string hatalitcnosifre {
            get {
                return ResourceManager.GetString("hatalitcnosifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalı T.C. numarası veya okul numarası!.
        /// </summary>
        internal static string hatalitcokulno {
            get {
                return ResourceManager.GetString("hatalitcokulno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoş geldiniz.
        /// </summary>
        internal static string hosgeldiniz {
            get {
                return ResourceManager.GetString("hosgeldiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres:.
        /// </summary>
        internal static string lbladdress {
            get {
                return ResourceManager.GetString("lbladdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Kayıt.
        /// </summary>
        internal static string lbladdstudent {
            get {
                return ResourceManager.GetString("lbladdstudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad:.
        /// </summary>
        internal static string lbladsoyad {
            get {
                return ResourceManager.GetString("lbladsoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen.
        /// </summary>
        internal static string lblakademisyen {
            get {
                return ResourceManager.GetString("lblakademisyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı:.
        /// </summary>
        internal static string lblakademisyenadi {
            get {
                return ResourceManager.GetString("lblakademisyenadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen Ara.
        /// </summary>
        internal static string lblakademisyenara {
            get {
                return ResourceManager.GetString("lblakademisyenara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKADEMİSYEN ARA.
        /// </summary>
        internal static string lblakademisyenaraformu {
            get {
                return ResourceManager.GetString("lblakademisyenaraformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen:.
        /// </summary>
        internal static string lblakademisyencombobox {
            get {
                return ResourceManager.GetString("lblakademisyencombobox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen Düzenle.
        /// </summary>
        internal static string lblakademisyenduzenle {
            get {
                return ResourceManager.GetString("lblakademisyenduzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKADEMİSYEN DÜZENLEME FORMU.
        /// </summary>
        internal static string lblakademisyenduzenlemeformu {
            get {
                return ResourceManager.GetString("lblakademisyenduzenlemeformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKADEMİSYEN GİRİŞ PANELİ.
        /// </summary>
        internal static string lblakademisyengirispaneli {
            get {
                return ResourceManager.GetString("lblakademisyengirispaneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen Kayıt.
        /// </summary>
        internal static string lblakademisyenkayit {
            get {
                return ResourceManager.GetString("lblakademisyenkayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKADEMİSYEN KAYIT FORMU.
        /// </summary>
        internal static string lblakademisyenkayitformu {
            get {
                return ResourceManager.GetString("lblakademisyenkayitformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyenler.
        /// </summary>
        internal static string lblakademisyenler {
            get {
                return ResourceManager.GetString("lblakademisyenler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen Listesi.
        /// </summary>
        internal static string lblakademisyenlistesi {
            get {
                return ResourceManager.GetString("lblakademisyenlistesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKADEMİSYEN LİSTESİ.
        /// </summary>
        internal static string lblakademisyenlistesiformu {
            get {
                return ResourceManager.GetString("lblakademisyenlistesiformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKADEMİSYENLER.
        /// </summary>
        internal static string lblakademisyenpanel {
            get {
                return ResourceManager.GetString("lblakademisyenpanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKADEMİSYEN PANELİ.
        /// </summary>
        internal static string lblakademisyenpaneli {
            get {
                return ResourceManager.GetString("lblakademisyenpaneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen Sayısı:.
        /// </summary>
        internal static string lblakademisyensayisi {
            get {
                return ResourceManager.GetString("lblakademisyensayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen Sil.
        /// </summary>
        internal static string lblakademisyensil {
            get {
                return ResourceManager.GetString("lblakademisyensil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKADEMİSYEN SİLME FORMU.
        /// </summary>
        internal static string lblakademisyensilmeformu {
            get {
                return ResourceManager.GetString("lblakademisyensilmeformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen Sırala (A-Z):.
        /// </summary>
        internal static string lblakademisyensirala {
            get {
                return ResourceManager.GetString("lblakademisyensirala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen Sırala (Z-A):.
        /// </summary>
        internal static string lblakademisyensiralaters {
            get {
                return ResourceManager.GetString("lblakademisyensiralaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadı:.
        /// </summary>
        internal static string lblakademisyensoyadi {
            get {
                return ResourceManager.GetString("lblakademisyensoyadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.C. No:.
        /// </summary>
        internal static string lblakademisyentcno {
            get {
                return ResourceManager.GetString("lblakademisyentcno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi:.
        /// </summary>
        internal static string lblbirthdate {
            get {
                return ResourceManager.GetString("lblbirthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Yeri:.
        /// </summary>
        internal static string lblbirthplace {
            get {
                return ResourceManager.GetString("lblbirthplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm:.
        /// </summary>
        internal static string lblbolum {
            get {
                return ResourceManager.GetString("lblbolum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm Adı:.
        /// </summary>
        internal static string lblbolumadi {
            get {
                return ResourceManager.GetString("lblbolumadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm Ara.
        /// </summary>
        internal static string lblbolumara {
            get {
                return ResourceManager.GetString("lblbolumara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm Düzenle.
        /// </summary>
        internal static string lblbolumduzenle {
            get {
                return ResourceManager.GetString("lblbolumduzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÖLÜM DÜZENLE.
        /// </summary>
        internal static string lblbolumduzenlemenu {
            get {
                return ResourceManager.GetString("lblbolumduzenlemenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm Ekle.
        /// </summary>
        internal static string lblbolumekle {
            get {
                return ResourceManager.GetString("lblbolumekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÖLÜM EKLE.
        /// </summary>
        internal static string lblbolumeklemenu {
            get {
                return ResourceManager.GetString("lblbolumeklemenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölümler.
        /// </summary>
        internal static string lblbolumler {
            get {
                return ResourceManager.GetString("lblbolumler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÖLÜMLER.
        /// </summary>
        internal static string lblbolumlerpanel {
            get {
                return ResourceManager.GetString("lblbolumlerpanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm Listesi.
        /// </summary>
        internal static string lblbolumlistesi {
            get {
                return ResourceManager.GetString("lblbolumlistesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm Sayısı:.
        /// </summary>
        internal static string lblbolumsayisi {
            get {
                return ResourceManager.GetString("lblbolumsayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm Sil.
        /// </summary>
        internal static string lblbolumsil {
            get {
                return ResourceManager.GetString("lblbolumsil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÖLÜM SİL.
        /// </summary>
        internal static string lblbolumsilmenu {
            get {
                return ResourceManager.GetString("lblbolumsilmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm Sırala (A-Z):.
        /// </summary>
        internal static string lblbolumsirala {
            get {
                return ResourceManager.GetString("lblbolumsirala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm Sırala (Z-A):.
        /// </summary>
        internal static string lblbolumsiralaters {
            get {
                return ResourceManager.GetString("lblbolumsiralaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl:.
        /// </summary>
        internal static string lblcity {
            get {
                return ResourceManager.GetString("lblcity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola Tekrar:.
        /// </summary>
        internal static string lblconfirmpassword {
            get {
                return ResourceManager.GetString("lblconfirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut Parola.
        /// </summary>
        internal static string lblcurrentpassword {
            get {
                return ResourceManager.GetString("lblcurrentpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Sil.
        /// </summary>
        internal static string lbldeletestudent {
            get {
                return ResourceManager.GetString("lbldeletestudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm:.
        /// </summary>
        internal static string lbldepartment {
            get {
                return ResourceManager.GetString("lbldepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders:.
        /// </summary>
        internal static string lblders {
            get {
                return ResourceManager.GetString("lblders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Ara.
        /// </summary>
        internal static string lbldersara {
            get {
                return ResourceManager.GetString("lbldersara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DERS ARA.
        /// </summary>
        internal static string lbldersaraformu {
            get {
                return ResourceManager.GetString("lbldersaraformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Ara:.
        /// </summary>
        internal static string lbldersarama {
            get {
                return ResourceManager.GetString("lbldersarama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Düzenle.
        /// </summary>
        internal static string lbldersduzenle {
            get {
                return ResourceManager.GetString("lbldersduzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DERS DÜZENLE.
        /// </summary>
        internal static string lbldersduzenleformu {
            get {
                return ResourceManager.GetString("lbldersduzenleformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Ekle.
        /// </summary>
        internal static string lbldersekle {
            get {
                return ResourceManager.GetString("lbldersekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DERS EKLE.
        /// </summary>
        internal static string lbldersekleformu {
            get {
                return ResourceManager.GetString("lbldersekleformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dersler.
        /// </summary>
        internal static string lbldersler {
            get {
                return ResourceManager.GetString("lbldersler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DERSLER.
        /// </summary>
        internal static string lblderslerpanel {
            get {
                return ResourceManager.GetString("lblderslerpanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Listesi.
        /// </summary>
        internal static string lblderslistesi {
            get {
                return ResourceManager.GetString("lblderslistesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DERS LİSTESİ.
        /// </summary>
        internal static string lblderslistesiformu {
            get {
                return ResourceManager.GetString("lblderslistesiformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Sayısı:.
        /// </summary>
        internal static string lblderssayisi {
            get {
                return ResourceManager.GetString("lblderssayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Seç:.
        /// </summary>
        internal static string lblderssec {
            get {
                return ResourceManager.GetString("lblderssec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Sil.
        /// </summary>
        internal static string lblderssil {
            get {
                return ResourceManager.GetString("lblderssil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DERS SİL.
        /// </summary>
        internal static string lblderssilformu {
            get {
                return ResourceManager.GetString("lblderssilformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Sırala (A-Z):.
        /// </summary>
        internal static string lblderssirala {
            get {
                return ResourceManager.GetString("lblderssirala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Sırala (Z-A):.
        /// </summary>
        internal static string lblderssiralaters {
            get {
                return ResourceManager.GetString("lblderssiralaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Değiştir.
        /// </summary>
        internal static string lbldildegistir {
            get {
                return ResourceManager.GetString("lbldildegistir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe:.
        /// </summary>
        internal static string lbldistrict {
            get {
                return ResourceManager.GetString("lbldistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru Ara.
        /// </summary>
        internal static string lblduyuruara {
            get {
                return ResourceManager.GetString("lblduyuruara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUYURU ARA.
        /// </summary>
        internal static string lblduyuruaraformu {
            get {
                return ResourceManager.GetString("lblduyuruaraformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru Ara:.
        /// </summary>
        internal static string lblduyuruarama {
            get {
                return ResourceManager.GetString("lblduyuruarama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru Başlığı:.
        /// </summary>
        internal static string lblduyurubasligi {
            get {
                return ResourceManager.GetString("lblduyurubasligi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru Düzenle.
        /// </summary>
        internal static string lblduyuruduzenle {
            get {
                return ResourceManager.GetString("lblduyuruduzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUYURU DÜZENLE.
        /// </summary>
        internal static string lblduyuruduzenleformu {
            get {
                return ResourceManager.GetString("lblduyuruduzenleformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik:.
        /// </summary>
        internal static string lblduyuruicerik {
            get {
                return ResourceManager.GetString("lblduyuruicerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyurular.
        /// </summary>
        internal static string lblduyurular {
            get {
                return ResourceManager.GetString("lblduyurular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyurular.
        /// </summary>
        internal static string lblduyurularogrenci {
            get {
                return ResourceManager.GetString("lblduyurularogrenci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUYURULAR.
        /// </summary>
        internal static string lblduyurularpanel {
            get {
                return ResourceManager.GetString("lblduyurularpanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru Listesi.
        /// </summary>
        internal static string lblduyurulistesi {
            get {
                return ResourceManager.GetString("lblduyurulistesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUYURU LİSTESİ.
        /// </summary>
        internal static string lblduyurulistesiformu {
            get {
                return ResourceManager.GetString("lblduyurulistesiformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru Oluştur.
        /// </summary>
        internal static string lblduyuruolustur {
            get {
                return ResourceManager.GetString("lblduyuruolustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUYURU OLUŞTUR.
        /// </summary>
        internal static string lblduyuruolusturformu {
            get {
                return ResourceManager.GetString("lblduyuruolusturformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru Sayısı:.
        /// </summary>
        internal static string lblduyurusayisi {
            get {
                return ResourceManager.GetString("lblduyurusayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru Sil.
        /// </summary>
        internal static string lblduyurusil {
            get {
                return ResourceManager.GetString("lblduyurusil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUYURU SİL.
        /// </summary>
        internal static string lblduyurusilformu {
            get {
                return ResourceManager.GetString("lblduyurusilformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Düzenle.
        /// </summary>
        internal static string lbleditstudent {
            get {
                return ResourceManager.GetString("lbleditstudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğitim Otomasyon Sistemi.
        /// </summary>
        internal static string lblegitimotomasyonsistemi {
            get {
                return ResourceManager.GetString("lblegitimotomasyonsistemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğitim Otomasyonu Giriş Panelleri.
        /// </summary>
        internal static string lblegitimotomasyonugirispanelleri {
            get {
                return ResourceManager.GetString("lblegitimotomasyonugirispanelleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baba Adı:.
        /// </summary>
        internal static string lblfathername {
            get {
                return ResourceManager.GetString("lblfathername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Sınavı:.
        /// </summary>
        internal static string lblfinalsinavi {
            get {
                return ResourceManager.GetString("lblfinalsinavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gazeteler.
        /// </summary>
        internal static string lblgazeteler {
            get {
                return ResourceManager.GetString("lblgazeteler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet:.
        /// </summary>
        internal static string lblgender {
            get {
                return ResourceManager.GetString("lblgender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenlik Kodu:.
        /// </summary>
        internal static string lblguvenlikkodu {
            get {
                return ResourceManager.GetString("lblguvenlikkodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Makinesi.
        /// </summary>
        internal static string lblhesapmakinesi {
            get {
                return ResourceManager.GetString("lblhesapmakinesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ev Telefonu:.
        /// </summary>
        internal static string lblhomephonenumber {
            get {
                return ResourceManager.GetString("lblhomephonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı:.
        /// </summary>
        internal static string lblkullaniciadi {
            get {
                return ResourceManager.GetString("lblkullaniciadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÖLÜM LİSTESİ.
        /// </summary>
        internal static string lbllistdepartmentmenu {
            get {
                return ResourceManager.GetString("lbllistdepartmentmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Listesi.
        /// </summary>
        internal static string lblliststudent {
            get {
                return ResourceManager.GetString("lblliststudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğitim Otomasyon Sistemi.
        /// </summary>
        internal static string lbllogineos {
            get {
                return ResourceManager.GetString("lbllogineos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Adresi:.
        /// </summary>
        internal static string lblmail {
            get {
                return ResourceManager.GetString("lblmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anne Adı:.
        /// </summary>
        internal static string lblmothername {
            get {
                return ResourceManager.GetString("lblmothername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müzik Dinle.
        /// </summary>
        internal static string lblmuzikdinle {
            get {
                return ResourceManager.GetString("lblmuzikdinle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müzikler.
        /// </summary>
        internal static string lblmuzikler {
            get {
                return ResourceManager.GetString("lblmuzikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semt:.
        /// </summary>
        internal static string lblneighborhood {
            get {
                return ResourceManager.GetString("lblneighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Parola.
        /// </summary>
        internal static string lblnewpassword {
            get {
                return ResourceManager.GetString("lblnewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Bilgileri.
        /// </summary>
        internal static string lblnotbilgileri {
            get {
                return ResourceManager.GetString("lblnotbilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT İŞLEMLERİ.
        /// </summary>
        internal static string lblnotislemleri {
            get {
                return ResourceManager.GetString("lblnotislemleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notlar.
        /// </summary>
        internal static string lblnotlar {
            get {
                return ResourceManager.GetString("lblnotlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTLARIM.
        /// </summary>
        internal static string lblnotlarim {
            get {
                return ResourceManager.GetString("lblnotlarim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci.
        /// </summary>
        internal static string lblogrenci {
            get {
                return ResourceManager.GetString("lblogrenci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞRENCİ ARA.
        /// </summary>
        internal static string lblogrenciarapanel {
            get {
                return ResourceManager.GetString("lblogrenciarapanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞRENCİ DÜZENLEME FORMU.
        /// </summary>
        internal static string lblogrenciduzenlemeformu {
            get {
                return ResourceManager.GetString("lblogrenciduzenlemeformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞRENCİ GİRİŞ PANELİ.
        /// </summary>
        internal static string lblogrencigirispaneli {
            get {
                return ResourceManager.GetString("lblogrencigirispaneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci ID:.
        /// </summary>
        internal static string lblogrenciid {
            get {
                return ResourceManager.GetString("lblogrenciid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenciler.
        /// </summary>
        internal static string lblogrenciler {
            get {
                return ResourceManager.GetString("lblogrenciler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞRENCİ LİSTESİ.
        /// </summary>
        internal static string lblogrencilistesiformu {
            get {
                return ResourceManager.GetString("lblogrencilistesiformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci No:.
        /// </summary>
        internal static string lblogrencino {
            get {
                return ResourceManager.GetString("lblogrencino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci No Ara:.
        /// </summary>
        internal static string lblogrencinoara {
            get {
                return ResourceManager.GetString("lblogrencinoara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞRENCİ PANELİ.
        /// </summary>
        internal static string lblogrencipaneli {
            get {
                return ResourceManager.GetString("lblogrencipaneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Sayısı:.
        /// </summary>
        internal static string lblogrencisayisi {
            get {
                return ResourceManager.GetString("lblogrencisayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞRENCİ SİLME FORMU.
        /// </summary>
        internal static string lblogrencisilmeformu {
            get {
                return ResourceManager.GetString("lblogrencisilmeformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Sırala (A-Z):.
        /// </summary>
        internal static string lblogrencisirala {
            get {
                return ResourceManager.GetString("lblogrencisirala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Sırala (Z-A):.
        /// </summary>
        internal static string lblogrencisiralaters {
            get {
                return ResourceManager.GetString("lblogrencisiralaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ortalama:.
        /// </summary>
        internal static string lblortalama {
            get {
                return ResourceManager.GetString("lblortalama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola:.
        /// </summary>
        internal static string lblparola {
            get {
                return ResourceManager.GetString("lblparola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola:.
        /// </summary>
        internal static string lblpassword {
            get {
                return ResourceManager.GetString("lblpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep Telefonu:.
        /// </summary>
        internal static string lblphonenumber {
            get {
                return ResourceManager.GetString("lblphonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoğraf:.
        /// </summary>
        internal static string lblphoto {
            get {
                return ResourceManager.GetString("lblphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posta Kodu:.
        /// </summary>
        internal static string lblpostalcode {
            get {
                return ResourceManager.GetString("lblpostalcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radyo.
        /// </summary>
        internal static string lblradyo {
            get {
                return ResourceManager.GetString("lblradyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporlar.
        /// </summary>
        internal static string lblraporlar {
            get {
                return ResourceManager.GetString("lblraporlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAPORLAR.
        /// </summary>
        internal static string lblraporlarpaneli {
            get {
                return ResourceManager.GetString("lblraporlarpaneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÖLÜM ARA.
        /// </summary>
        internal static string lblsearchdepartmentmenu {
            get {
                return ResourceManager.GetString("lblsearchdepartmentmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Ara.
        /// </summary>
        internal static string lblsearchstudent {
            get {
                return ResourceManager.GetString("lblsearchstudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞİFRE DEĞİŞİKLİĞİ.
        /// </summary>
        internal static string lblsifredegisikliği {
            get {
                return ResourceManager.GetString("lblsifredegisikliği", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Değiştir.
        /// </summary>
        internal static string lblsifredegistir {
            get {
                return ResourceManager.GetString("lblsifredegistir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son 3 Akademisyen Kayıt:.
        /// </summary>
        internal static string lblson3akademisyenkayit {
            get {
                return ResourceManager.GetString("lblson3akademisyenkayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son 3 Bölüm Kayıt:.
        /// </summary>
        internal static string lblson3bolumkayit {
            get {
                return ResourceManager.GetString("lblson3bolumkayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son 3 Ders Kayıt:.
        /// </summary>
        internal static string lblson3derskayit {
            get {
                return ResourceManager.GetString("lblson3derskayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son 3 Öğrenci Kayıt:.
        /// </summary>
        internal static string lblson3ogrencikayit {
            get {
                return ResourceManager.GetString("lblson3ogrencikayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci:.
        /// </summary>
        internal static string lblstudent {
            get {
                return ResourceManager.GetString("lblstudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Adı:.
        /// </summary>
        internal static string lblstudentname {
            get {
                return ResourceManager.GetString("lblstudentname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okul Numarası:.
        /// </summary>
        internal static string lblstudentnumber {
            get {
                return ResourceManager.GetString("lblstudentnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞRENCİLER.
        /// </summary>
        internal static string lblstudentpanel {
            get {
                return ResourceManager.GetString("lblstudentpanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞRENCİ KAYIT FORMU.
        /// </summary>
        internal static string lblstudentregistrationform {
            get {
                return ResourceManager.GetString("lblstudentregistrationform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Soyadı:.
        /// </summary>
        internal static string lblstudentsurname {
            get {
                return ResourceManager.GetString("lblstudentsurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.C. No:.
        /// </summary>
        internal static string lblstudenttrno {
            get {
                return ResourceManager.GetString("lblstudenttrno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.C. Kimlik No:.
        /// </summary>
        internal static string lbltcno {
            get {
                return ResourceManager.GetString("lbltcno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.C. No Ara:.
        /// </summary>
        internal static string lbltcnoara {
            get {
                return ResourceManager.GetString("lbltcnoara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Akademisyen Sayısı:.
        /// </summary>
        internal static string lbltoplamakademisyensayisi {
            get {
                return ResourceManager.GetString("lbltoplamakademisyensayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Bölüm Sayısı:.
        /// </summary>
        internal static string lbltoplambolumsayisi {
            get {
                return ResourceManager.GetString("lbltoplambolumsayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Ders Sayısı:.
        /// </summary>
        internal static string lbltoplamderssayisi {
            get {
                return ResourceManager.GetString("lbltoplamderssayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Öğrenci Sayısı:.
        /// </summary>
        internal static string lbltoplamogrencisayisi {
            get {
                return ResourceManager.GetString("lbltoplamogrencisayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamalar.
        /// </summary>
        internal static string lbluygulamalar {
            get {
                return ResourceManager.GetString("lbluygulamalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UYGULAMALAR.
        /// </summary>
        internal static string lbluygulamalarformu {
            get {
                return ResourceManager.GetString("lbluygulamalarformu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vize Sınavı:.
        /// </summary>
        internal static string lblvizesinavi {
            get {
                return ResourceManager.GetString("lblvizesinavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici.
        /// </summary>
        internal static string lblyonetici {
            get {
                return ResourceManager.GetString("lblyonetici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici:.
        /// </summary>
        internal static string lblyoneticibasligi {
            get {
                return ResourceManager.GetString("lblyoneticibasligi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YÖNETİCİ GİRİŞ PANELİ.
        /// </summary>
        internal static string lblyoneticigirispaneli {
            get {
                return ResourceManager.GetString("lblyoneticigirispaneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YÖNETİCİ PANELİ.
        /// </summary>
        internal static string lblyoneticipaneli {
            get {
                return ResourceManager.GetString("lblyoneticipaneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YÜKLENİYOR.
        /// </summary>
        internal static string lblyukleniyor {
            get {
                return ResourceManager.GetString("lblyukleniyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMİZLE.
        /// </summary>
        internal static string LnkLblClear {
            get {
                return ResourceManager.GetString("LnkLblClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GİRİŞ YAP.
        /// </summary>
        internal static string LnkLblLogin {
            get {
                return ResourceManager.GetString("LnkLblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail adresi boş bırakılamaz..
        /// </summary>
        internal static string mailbos {
            get {
                return ResourceManager.GetString("mailbos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programdan çıkmak istiyor musunuz?.
        /// </summary>
        internal static string metin {
            get {
                return ResourceManager.GetString("metin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş başarılı, admin paneline yönlendiriliyorsunuz..
        /// </summary>
        internal static string metin2 {
            get {
                return ResourceManager.GetString("metin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş başarılı, akademisyen paneline yönlendiriliyorsunuz..
        /// </summary>
        internal static string metin3 {
            get {
                return ResourceManager.GetString("metin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş başarılı, öğrenci paneline yönlendiriliyorsunuz..
        /// </summary>
        internal static string metin4 {
            get {
                return ResourceManager.GetString("metin4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğitim Otomasyon Sistemi Yönetici Paneli.
        /// </summary>
        internal static string notifyIcon1 {
            get {
                return ResourceManager.GetString("notifyIcon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğitim Otomasyon Sistemi Akademisyen Paneli.
        /// </summary>
        internal static string notifyIcon2 {
            get {
                return ResourceManager.GetString("notifyIcon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğitim Otomasyon Sistemi Öğrenci Paneli.
        /// </summary>
        internal static string notifyIcon3 {
            get {
                return ResourceManager.GetString("notifyIcon3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğitim Otomasyon Sistemi Akademisyen Paneli.
        /// </summary>
        internal static string notifyiconakademisyentext {
            get {
                return ResourceManager.GetString("notifyiconakademisyentext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program sağ alt köşede konumlandı..
        /// </summary>
        internal static string notifyiconballoontiptext {
            get {
                return ResourceManager.GetString("notifyiconballoontiptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğitim Otomasyon Sistemi arka planda çalışıyor.
        /// </summary>
        internal static string notifyiconballoontiptitle {
            get {
                return ResourceManager.GetString("notifyiconballoontiptitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğitim Otomasyon Sistemi Öğrenci Paneli.
        /// </summary>
        internal static string notifyiconogrencitext {
            get {
                return ResourceManager.GetString("notifyiconogrencitext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğitim Otomasyon Sistemi Yönetici Paneli.
        /// </summary>
        internal static string notifyiconyoneticitext {
            get {
                return ResourceManager.GetString("notifyiconyoneticitext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci adı en az 2 karakter olmalıdır..
        /// </summary>
        internal static string ogrenciadi2karakterdenaz {
            get {
                return ResourceManager.GetString("ogrenciadi2karakterdenaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci adı boş bırakılamaz..
        /// </summary>
        internal static string ogrenciadibos {
            get {
                return ResourceManager.GetString("ogrenciadibos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir öğrenci seçiniz..
        /// </summary>
        internal static string ogrencibos {
            get {
                return ResourceManager.GetString("ogrencibos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci panelinden çıkmak istiyor musunuz?.
        /// </summary>
        internal static string ogrencicikis {
            get {
                return ResourceManager.GetString("ogrencicikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Yeri boş bırakılamaz..
        /// </summary>
        internal static string ogrencidogumyeribos {
            get {
                return ResourceManager.GetString("ogrencidogumyeribos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} numaralı öğrenci başarılı bir şekilde güncellendi..
        /// </summary>
        internal static string ogrenciguncellendi {
            get {
                return ResourceManager.GetString("ogrenciguncellendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} numaralı öğrenci başarılı bir şekilde kaydedildi..
        /// </summary>
        internal static string ogrencikaydedildi {
            get {
                return ResourceManager.GetString("ogrencikaydedildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders notu başarılı bir şekilde güncellendi..
        /// </summary>
        internal static string ogrencinotuguncellendi {
            get {
                return ResourceManager.GetString("ogrencinotuguncellendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders notu başarılı bir şekilde kaydedildi..
        /// </summary>
        internal static string ogrencinotukaydedildi {
            get {
                return ResourceManager.GetString("ogrencinotukaydedildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci numarası boş bırakılamaz..
        /// </summary>
        internal static string ogrencinumarabos {
            get {
                return ResourceManager.GetString("ogrencinumarabos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} numaralı öğrenciyi silmek istiyor musunuz?.
        /// </summary>
        internal static string ogrencisil {
            get {
                return ResourceManager.GetString("ogrencisil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} numaralı öğrenci başarılı bir şekilde silindi..
        /// </summary>
        internal static string ogrencisilindi {
            get {
                return ResourceManager.GetString("ogrencisilindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen silmek istediğiniz bir öğrenci seçiniz..
        /// </summary>
        internal static string ogrencisilmebos {
            get {
                return ResourceManager.GetString("ogrencisilmebos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci soyadı en az 2 karakter olmalıdır..
        /// </summary>
        internal static string ogrencisoyadi2karakterdenaz {
            get {
                return ResourceManager.GetString("ogrencisoyadi2karakterdenaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci soyadı boş bırakılamaz..
        /// </summary>
        internal static string ogrencisoyadibos {
            get {
                return ResourceManager.GetString("ogrencisoyadibos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrencinin üniversiteye kaydolması için yaşı 17 olmalıdır..
        /// </summary>
        internal static string ogrenciuniversiteyasi {
            get {
                return ResourceManager.GetString("ogrenciuniversiteyasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir parola belirleyin..
        /// </summary>
        internal static string parolabos {
            get {
                return ResourceManager.GetString("parolabos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolalar uyuşmuyor!.
        /// </summary>
        internal static string parolalaraynidegil {
            get {
                return ResourceManager.GetString("parolalaraynidegil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola Tekrar kısmı boş bırakılamaz..
        /// </summary>
        internal static string parolatekrarbos {
            get {
                return ResourceManager.GetString("parolatekrarbos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posta kodu boş bırakılamaz..
        /// </summary>
        internal static string postakodubos {
            get {
                return ResourceManager.GetString("postakodubos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İNGİLİZCE.
        /// </summary>
        internal static string rdbenglish {
            get {
                return ResourceManager.GetString("rdbenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kadın.
        /// </summary>
        internal static string RdbFemale {
            get {
                return ResourceManager.GetString("RdbFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erkek.
        /// </summary>
        internal static string RdbMale {
            get {
                return ResourceManager.GetString("RdbMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÜRKÇE.
        /// </summary>
        internal static string rdbturkce {
            get {
                return ResourceManager.GetString("rdbturkce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir fotoğraf seçiniz..
        /// </summary>
        internal static string resimbos {
            get {
                return ResourceManager.GetString("resimbos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semt boş bırakılamaz..
        /// </summary>
        internal static string semtbos {
            get {
                return ResourceManager.GetString("semtbos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.C. Kimlik Numarası boş bırakılamaz..
        /// </summary>
        internal static string tcnobos {
            get {
                return ResourceManager.GetString("tcnobos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep Telefonu Numarası boş bırakılamaz..
        /// </summary>
        internal static string telefonnobos {
            get {
                return ResourceManager.GetString("telefonnobos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm ekleme, silme veya güncelleme işlemleri için tıklayın..
        /// </summary>
        internal static string toolTip1_SetToolTip {
            get {
                return ResourceManager.GetString("toolTip1.SetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüm İşlemleri.
        /// </summary>
        internal static string toolTip1_ToolTipTitle {
            get {
                return ResourceManager.GetString("toolTip1.ToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radyo, müzik dinleme gibi araçlar için tıklayın..
        /// </summary>
        internal static string toolTip10_SetToolTip {
            get {
                return ResourceManager.GetString("toolTip10.SetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamalar.
        /// </summary>
        internal static string toolTip10_ToolTipTitle {
            get {
                return ResourceManager.GetString("toolTip10.ToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporları görmek için tıklayın..
        /// </summary>
        internal static string toolTip11_SetToolTip {
            get {
                return ResourceManager.GetString("toolTip11.SetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporlar.
        /// </summary>
        internal static string toolTip11_ToolTipTitle {
            get {
                return ResourceManager.GetString("toolTip11.ToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simge Durumuna.
        /// </summary>
        internal static string toolTip12_SetToolTip {
            get {
                return ResourceManager.GetString("toolTip12.SetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        internal static string toolTip13_SetToolTip {
            get {
                return ResourceManager.GetString("toolTip13.SetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru oluşturmak için tıklayın..
        /// </summary>
        internal static string toolTip14_SetToolTip {
            get {
                return ResourceManager.GetString("toolTip14.SetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru İşlemleri.
        /// </summary>
        internal static string toolTip14_ToolTipTitle {
            get {
                return ResourceManager.GetString("toolTip14.ToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre değişikliği, radyo, müzik dinleme gibi araçlar için tıklayın..
        /// </summary>
        internal static string toolTip2_SetToolTip {
            get {
                return ResourceManager.GetString("toolTip2.SetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamalar.
        /// </summary>
        internal static string toolTip2_ToolTipTitle {
            get {
                return ResourceManager.GetString("toolTip2.ToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru oluşturma, silme veya güncelleme işlemleri için tıklayın..
        /// </summary>
        internal static string toolTip3_SetToolTip {
            get {
                return ResourceManager.GetString("toolTip3.SetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru İşlemleri.
        /// </summary>
        internal static string toolTip3_ToolTipTitle {
            get {
                return ResourceManager.GetString("toolTip3.ToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci ekleme, silme veya güncelleme işlemleri için tıklayın..
        /// </summary>
        internal static string toolTip4_SetToolTip {
            get {
                return ResourceManager.GetString("toolTip4.SetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci İşlemleri.
        /// </summary>
        internal static string toolTip4_ToolTipTitle {
            get {
                return ResourceManager.GetString("toolTip4.ToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen ekleme, silme veya güncelleme işlemleri için tıklayın..
        /// </summary>
        internal static string toolTip5_SetToolTip {
            get {
                return ResourceManager.GetString("toolTip5.SetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademisyen İşlemleri.
        /// </summary>
        internal static string toolTip5_ToolTipTitle {
            get {
                return ResourceManager.GetString("toolTip5.ToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders ekleme, silme veya güncelleme işlemleri için tıklayın..
        /// </summary>
        internal static string toolTip6_SetToolTip {
            get {
                return ResourceManager.GetString("toolTip6.SetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders İşlemleri.
        /// </summary>
        internal static string toolTip6_ToolTipTitle {
            get {
                return ResourceManager.GetString("toolTip6.ToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not ekleme, güncelleme işlemleri için tıklayın..
        /// </summary>
        internal static string toolTip7_SetToolTip {
            get {
                return ResourceManager.GetString("toolTip7.SetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not İşlemleri.
        /// </summary>
        internal static string toolTip7_ToolTipTitle {
            get {
                return ResourceManager.GetString("toolTip7.ToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not görüntülemek için tıklayın..
        /// </summary>
        internal static string toolTip8_SetToolTip {
            get {
                return ResourceManager.GetString("toolTip8.SetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Bilgileri.
        /// </summary>
        internal static string toolTip8_ToolTipTitle {
            get {
                return ResourceManager.GetString("toolTip8.ToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncel duyuruları görmek için tıklayın..
        /// </summary>
        internal static string toolTip9_SetToolTip {
            get {
                return ResourceManager.GetString("toolTip9.SetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuruları Gör.
        /// </summary>
        internal static string toolTip9_ToolTipTitle {
            get {
                return ResourceManager.GetString("toolTip9.ToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        internal static string uyari {
            get {
                return ResourceManager.GetString("uyari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici panelinden çıkmak istiyor musunuz?.
        /// </summary>
        internal static string yoneticicikis {
            get {
                return ResourceManager.GetString("yoneticicikis", resourceCulture);
            }
        }
    }
}
